# Generated by Django 4.2.1 on 2023-05-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='emp_safdar',
        ),
    ]
