# Generated by Django 4.2.1 on 2023-05-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='meterreaderregistration',
        ),
    ]
