# Generated by Django 4.2.1 on 2023-05-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
