# Generated by Django 4.2.1 on 2023-05-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_alter_employee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.EmailField(max_length=254),
        ),
    ]
